# ─────────────────────────────────────────────────────────────
#  相关文章推荐
# ─────────────────────────────────────────────────────────────
[related]
    threshold = 20
    includeNewer = true
    toLower = false

    [[related.indices]]
        name   = "tags"
        weight = 100

    [[related.indices]]
        name   = "categories"
        weight = 80
